export const LOCAL_FULL_PHOTOS: Record<string, any> = {
  'Akai-Professional/MPC-Sample': require('./Akai-Professional/MPC-Sample/photo.png'),
  'Arturia/Astrolab-88': require('./Arturia/Astrolab-88/photo.png'),
  'Arturia/DRUMBRUTE-IMPACT': require('./Arturia/DRUMBRUTE-IMPACT/photo.png'),
  'Arturia/MINIBRUTE-2S': require('./Arturia/MINIBRUTE-2S/photo.png'),
  'Arturia/MicroFreak': require('./Arturia/MicroFreak/photo.png'),
  'Arturia/Microbrute UFO': require('./Arturia/Microbrute UFO/photo.png'),
  'Arturia/Microfreak Vocoder': require('./Arturia/Microfreak Vocoder/photo.png'),
  'Arturia/MiniBrute-2-desktop': require('./Arturia/MiniBrute-2-desktop/photo.png'),
  'Arturia/Minifreak': require('./Arturia/Minifreak/photo.png'),
  'Arturia/Polybrute-12': require('./Arturia/Polybrute-12/photo.png'),
  'Behringer/CAT': require('./Behringer/CAT/photo.png'),
  'Behringer/CRAVE': require('./Behringer/CRAVE/photo.png'),
  'Behringer/JT-4000-MICRO': require('./Behringer/JT-4000-MICRO/photo.png'),
  'Behringer/K-2': require('./Behringer/K-2/photo.png'),
  'Behringer/KOBOL': require('./Behringer/KOBOL/photo.png'),
  'Behringer/MODEL-D': require('./Behringer/MODEL-D/photo.png'),
  'Behringer/MONO:POLY': require('./Behringer/MONO:POLY/photo.png'),
  'Behringer/MS-1': require('./Behringer/MS-1/photo.png'),
  'Behringer/NEUTRON': require('./Behringer/NEUTRON/photo.png'),
  'Behringer/PRO-1': require('./Behringer/PRO-1/photo.png'),
  'Behringer/PRO-800': require('./Behringer/PRO-800/photo.png'),
  'Behringer/PRO-VS-MINI': require('./Behringer/PRO-VS-MINI/photo.png'),
  'Behringer/RD-8-MKII': require('./Behringer/RD-8-MKII/photo.png'),
  'Behringer/RD-9': require('./Behringer/RD-9/photo.png'),
  'Behringer/RD6': require('./Behringer/RD6/photo.png'),
  'Behringer/SOLINA-STRING-ENSEMBLE': require('./Behringer/SOLINA-STRING-ENSEMBLE/photo.png'),
  'Behringer/TD3-MO-SR': require('./Behringer/TD3-MO-SR/photo.png'),
  'Behringer/TORO': require('./Behringer/TORO/photo.png'),
  'Behringer/VOCODER-VC-340': require('./Behringer/VOCODER-VC-340/photo.png'),
  'Behringer/WASP-DELUXE': require('./Behringer/WASP-DELUXE/photo.png'),
  'Black-Corporation/Deckard\'s-dream-MKII': require('./Black-Corporation/Deckard\'s-dream-MKII/photo.png'),
  'Black-Corporation/Expander-MKII': require('./Black-Corporation/Expander-MKII/photo.png'),
  'Buchla/System-24': require('./Buchla/System-24/photo.png'),
  'Dreadbox/ARTEMIS': require('./Dreadbox/ARTEMIS/photo.png'),
  'Dreadbox/EREBUS': require('./Dreadbox/EREBUS/photo.png'),
  'Dreadbox/HADES': require('./Dreadbox/HADES/photo.png'),
  'Dreadbox/NYMPHES': require('./Dreadbox/NYMPHES/photo.png'),
  'Dreadbox/TYPHON': require('./Dreadbox/TYPHON/photo.png'),
  'EMS/VCS-3': require('./EMS/VCS-3/photo.png'),
  'Elektron/Digitakt': require('./Elektron/Digitakt/photo.png'),
  'Elektron/MODEL-CYCLES': require('./Elektron/MODEL-CYCLES/photo.png'),
  'Elektron/MODEL-SAMPLES': require('./Elektron/MODEL-SAMPLES/photo.png'),
  'Erica-Synths/Perkons-01': require('./Erica-Synths/Perkons-01/photo.png'),
  'Expressive-E/OSMOSE-CE': require('./Expressive-E/OSMOSE-CE/photo.png'),
  'Jomox/Alpha-Base-09': require('./Jomox/Alpha-Base-09/photo.png'),
  'Korg/Drumlogue': require('./Korg/Drumlogue/photo.png'),
  'Korg/Electribe-2-BL': require('./Korg/Electribe-2-BL/photo.png'),
  'Korg/KORG-ARP-2600-FS': require('./Korg/KORG-ARP-2600-FS/photo.png'),
  'Korg/Keystage-49': require('./Korg/Keystage-49/photo.png'),
  'Korg/Keystage-61': require('./Korg/Keystage-61/photo.png'),
  'Korg/MS20-mini': require('./Korg/MS20-mini/photo.png'),
  'Korg/Minilogue-XD-module': require('./Korg/Minilogue-XD-module/photo.png'),
  'Korg/Modwave-mk2-desktop': require('./Korg/Modwave-mk2-desktop/photo.png'),
  'Korg/Monologue': require('./Korg/Monologue/photo.png'),
  'Korg/MultiPoly-desktop': require('./Korg/MultiPoly-desktop/photo.png'),
  'Korg/Opsix-mkII-desktop': require('./Korg/Opsix-mkII-desktop/photo.png'),
  'Korg/PS-3300': require('./Korg/PS-3300/photo.png'),
  'Korg/Phase-8': require('./Korg/Phase-8/photo.png'),
  'Korg/VOLCA-BEATS': require('./Korg/VOLCA-BEATS/photo.png'),
  'Korg/VOLCA-DRUM': require('./Korg/VOLCA-DRUM/photo.png'),
  'Korg/VOLCA-FM2': require('./Korg/VOLCA-FM2/photo.png'),
  'Korg/VOLCA-KEYS': require('./Korg/VOLCA-KEYS/photo.png'),
  'Korg/VOLCA-KICK': require('./Korg/VOLCA-KICK/photo.png'),
  'Korg/VOLCA-MODULAR': require('./Korg/VOLCA-MODULAR/photo.png'),
  'Korg/VOLCA-NUBASS': require('./Korg/VOLCA-NUBASS/photo.png'),
  'Korg/VOLCA-SAMPLE-MKII': require('./Korg/VOLCA-SAMPLE-MKII/photo.png'),
  'Korg/Volca FM Rev2': require('./Korg/Volca FM Rev2/photo.png'),
  'Korg/Volca Sample Rev2': require('./Korg/Volca Sample Rev2/photo.png'),
  'Korg/Volca-Bass': require('./Korg/Volca-Bass/photo.png'),
  'Korg/Wavestate-MkII-desktop': require('./Korg/Wavestate-MkII-desktop/photo.png'),
  'Moog/Model-D-(Moog)': require('./Moog/Model-D-(Moog)/photo.png'),
  'Moog/Subsequent-37': require('./Moog/Subsequent-37/photo.png'),
  'Nord/Nord-Drum-3p': require('./Nord/Nord-Drum-3p/photo.png'),
  'Nord/Nord-Stage-4-88': require('./Nord/Nord-Stage-4-88/photo.png'),
  'Nord/Nord-Wave-2': require('./Nord/Nord-Wave-2/photo.png'),
  'Novation/Bass-Station': require('./Novation/Bass-Station/photo.png'),
  'Novation/Peak-module': require('./Novation/Peak-module/photo.png'),
  'Oberheim/OBX-8-DESKTOP': require('./Oberheim/OBX-8-DESKTOP/photo.png'),
  'Oberheim/TEO-5-desktop': require('./Oberheim/TEO-5-desktop/photo.png'),
  'PWM/MALEVOLENT': require('./PWM/MALEVOLENT/photo.png'),
  'Polyend/Polyend-Drums': require('./Polyend/Polyend-Drums/photo.png'),
  'Rhodes/RHODES-MK8': require('./Rhodes/RHODES-MK8/photo.png'),
  'Roland/AIRA-J-6': require('./Roland/AIRA-J-6/photo.png'),
  'Roland/AIRA-S-1': require('./Roland/AIRA-S-1/photo.png'),
  'Roland/AIRA-T-8': require('./Roland/AIRA-T-8/photo.png'),
  'Roland/JD-08': require('./Roland/JD-08/photo.png'),
  'Roland/JU-06A': require('./Roland/JU-06A/photo.png'),
  'Roland/JX-08': require('./Roland/JX-08/photo.png'),
  'Roland/MC-101': require('./Roland/MC-101/photo.png'),
  'Roland/SE-02': require('./Roland/SE-02/photo.png'),
  'Roland/SH-01A': require('./Roland/SH-01A/photo.png'),
  'Roland/SP-404-MKII': require('./Roland/SP-404-MKII/photo.png'),
  'Roland/TB-03': require('./Roland/TB-03/photo.png'),
  'Roland/TR-06': require('./Roland/TR-06/photo.png'),
  'Roland/TR-08': require('./Roland/TR-08/photo.png'),
  'Roland/TR-1000': require('./Roland/TR-1000/photo.png'),
  'Roland/TR-6S': require('./Roland/TR-6S/photo.png'),
  'SOMA-Laboratory/Pulsar-23': require('./SOMA-Laboratory/Pulsar-23/photo.png'),
  'Sequential/OB6-Module': require('./Sequential/OB6-Module/photo.png'),
  'Sequential/Pro-3-SE': require('./Sequential/Pro-3-SE/photo.png'),
  'Sequential/Prophet-10-module': require('./Sequential/Prophet-10-module/photo.png'),
  'Sequential/Take-5-desktop': require('./Sequential/Take-5-desktop/photo.png'),
  'Sequential/Trigon-6-module': require('./Sequential/Trigon-6-module/photo.png'),
  'Teenage Engineering/PO-12 rhythm': require('./Teenage Engineering/PO-12 rhythm/photo.png'),
  'Teenage Engineering/PO-14 sub': require('./Teenage Engineering/PO-14 sub/photo.png'),
  'Teenage Engineering/PO-16 factory': require('./Teenage Engineering/PO-16 factory/photo.png'),
  'Teenage Engineering/PO-20 arcade': require('./Teenage Engineering/PO-20 arcade/photo.png'),
  'Teenage Engineering/PO-24 office': require('./Teenage Engineering/PO-24 office/photo.png'),
  'Teenage Engineering/PO-28 robot': require('./Teenage Engineering/PO-28 robot/photo.png'),
  'Teenage Engineering/PO-32 tonic': require('./Teenage Engineering/PO-32 tonic/photo.png'),
  'Teenage Engineering/PO-33 K.O': require('./Teenage Engineering/PO-33 K.O/photo.png'),
  'Teenage Engineering/PO-35 speak': require('./Teenage Engineering/PO-35 speak/photo.png'),
  'Teenage-Engineering/EP-2350': require('./Teenage-Engineering/EP-2350/photo.png'),
  'Teenage-Engineering/EP-404-KO-II': require('./Teenage-Engineering/EP-404-KO-II/photo.png'),
  'Teenage-Engineering/EP-404-Medieval': require('./Teenage-Engineering/EP-404-Medieval/photo.png'),
  'Teenage-Engineering/EP-404-Riddim': require('./Teenage-Engineering/EP-404-Riddim/photo.png'),
  'Vermona/Drumding': require('./Vermona/Drumding/photo.png'),
  'Vermona/KICK-LANCET': require('./Vermona/KICK-LANCET/photo.png'),
  'Waldorf/Blofeld': require('./Waldorf/Blofeld/photo.png'),
  'Waldorf/PROTEIN': require('./Waldorf/PROTEIN/photo.png'),
  'Waldorf/STREICHFETT': require('./Waldorf/STREICHFETT/photo.png'),
};
